#pragma once
#define PARTICLE_RADIUS 1.2e-3f
#define PARTICLE_COUNT 75000

#define WINDOW_SIZE_X 1000
#define WINDOW_SIZE_Y 1000

// Computational constants
#define RESERVE_UNITS_PER_COLLISION_GRID_CELL 0
#define COMPUTE_PER_RENDER 5

#define COLLISIO_GLOBAL_NUM_ITERATIONS 2
#define COLLISION_CELL_NUM_ITERATIONS 3

#define RESERVE_SURROUNDING_PARTCILES 12
#define RESERVE_CURRENT_CELL_PARTICLES 2

// Physics constants
#define GRAVITY (1e-1f)
#define DT (5e-5)




// Debug constants
// #define CHECK_GRID_UPDATE_PARTICLE_INDICES_FOR_BOUNDS